// Design-diversity fixtures — 12 realistic BusinessProfiles spanning the six
// verticals. Shared by scripts/eval-design-diversity.mjs (structural
// assertions) and src/routes/demo.gallery.tsx (visual QA). Photo URLs are
// deterministic placeholders; the eval never fetches them.
import type { BusinessProfile } from "@/lib/demoApi";

function photos(seed: string, n: number): string[] {
  return Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i + 1}/900/600`);
}

export const DESIGN_FIXTURES: BusinessProfile[] = [
  // ── restaurant-hospitality × 4 ─────────────────────────────────────
  {
    vertical: "restaurant-hospitality",
    businessName: "Souther Williams Vineyard",
    businessNameSource: "google_places",
    tagline: "Estate wines poured where they were grown.",
    heroHeadline: "Sip estate wines above the French Broad valley",
    heroSub: "A working vineyard with tastings, live music weekends, and long views over the rows.",
    ctaLabel: "Visit Us",
    services: [
      { name: "Wine Tastings", blurb: "Guided flights of our estate-grown vintages." },
      { name: "Vineyard Tours", blurb: "Walk the rows and the crush pad with our winemaker." },
      { name: "Live Music Weekends", blurb: "Local acts on the lawn every Saturday." },
      { name: "Private Events", blurb: "Weddings and gatherings among the vines." },
    ],
    about: "We're a family vineyard crafting estate wines with a premium tasting-room experience overlooking the valley.",
    hoursLine: "Open today 12pm–7pm",
    serviceAreaLine: "Serving Fletcher, NC",
    reviews: [
      { quote: "Gorgeous views and the dry riesling is exceptional. A hidden gem.", author: "Dana W.", rating: 5 },
      { quote: "Lovely tasting flight, friendly staff, and live music on the lawn.", author: "Marcus H.", rating: 5 },
      { quote: "Beautiful spot for an afternoon — bring a picnic.", author: "Priya S.", rating: 4 },
    ],
    phone: "(828) 555-0141",
    address: "196 Estate Dr, Fletcher, NC",
    photoUrls: photos("vineyard", 6),
    rating: 4.8,
    reviewCount: 31,
    designBrief: {
      personality: ["elegant", "scenic", "relaxed"],
      audience: "wine lovers and weekend day-trippers",
      pricePosition: "premium",
      conversionGoal: "visit",
    },
  },
  {
    vertical: "restaurant-hospitality",
    businessName: "Tony's Slice House",
    businessNameSource: "google_places",
    tagline: "Big slices, small prices.",
    heroHeadline: "Hot slices out the window till midnight",
    heroSub: "New York style pies by the slice or whole, with $2 garlic knots and fountain sodas.",
    ctaLabel: "Order Online",
    services: [
      { name: "Cheese Slice", blurb: "The classic — thin, foldable, blistered crust." },
      { name: "Pepperoni Pie", blurb: "18-inch, cup-and-char pepperoni." },
      { name: "Garlic Knots", blurb: "Six to an order, extra parm." },
      { name: "Order online for pickup", blurb: "Skip the line — order pickup or delivery." },
    ],
    about: "We're a counter-service slice shop keeping it cheap, fast, and open late for the neighborhood.",
    hoursLine: "Open today 11am–12am",
    serviceAreaLine: "Serving Asheville, NC",
    reviews: [
      { quote: "Best cheap slice in town, no contest.", author: "Jess R.", rating: 5 },
      { quote: "Fast, greasy in the right way, open late.", author: "Coby T.", rating: 4 },
    ],
    phone: "(828) 555-0177",
    address: "88 Patton Ave, Asheville, NC",
    photoUrls: photos("slicehouse", 2),
    rating: 4.4,
    reviewCount: 212,
    designBrief: {
      personality: ["casual", "fast", "cheap"],
      audience: "late-night locals and students",
      pricePosition: "budget",
      conversionGoal: "order",
    },
  },
  {
    vertical: "restaurant-hospitality",
    businessName: "Willow & Bean Cafe",
    businessNameSource: "site_title",
    tagline: "Slow mornings, good coffee.",
    heroHeadline: "House-roasted coffee and scratch-made pastries",
    heroSub: "A neighborhood cafe with single-origin pour-overs, sourdough toasts, and a sunny patio.",
    ctaLabel: "Visit Us",
    services: [
      { name: "Pour-Over Bar", blurb: "Rotating single-origin beans, roasted in-house." },
      { name: "Breakfast Toasts", blurb: "Sourdough with seasonal toppings until 2pm." },
      { name: "Pastry Case", blurb: "Croissants and scones baked every morning." },
    ],
    about: "We're a small cafe roasting our own beans and baking everything from scratch each morning.",
    hoursLine: "Open today 7am–3pm",
    serviceAreaLine: "Serving Hendersonville, NC",
    reviews: [
      { quote: "The cardamom bun is worth the drive alone.", author: "Anna L.", rating: 5 },
      { quote: "Great coffee, calm space to work.", author: "Theo B.", rating: 5 },
    ],
    phone: "(828) 555-0122",
    address: "412 Main St, Hendersonville, NC",
    photoUrls: photos("willowbean", 3),
    rating: 4.7,
    reviewCount: 89,
    designBrief: {
      personality: ["cozy", "warm", "unhurried"],
      audience: "regulars and remote workers",
      pricePosition: "mid",
      conversionGoal: "visit",
    },
    // DNA v2 — full agent-authored schema exercising the schema-adoption path:
    // hero.variant (editorial-quote, previously never rendered), typeDNA,
    // gridFamily, chrome, servicesFraming, and an authored section list.
    designSchema: {
      positioning: {
        audience: "regulars and remote workers",
        valueProp: "House-roasted coffee and scratch pastries in a calm neighborhood room.",
        localContext: "Main St, Hendersonville NC — courthouse foot traffic, weekend day-trippers.",
        competitors: [{ name: "Black Bear Coffee", takeaway: "Generic green palette, stock photos." }],
        differentiators: ["roasts in-house", "everything baked same morning", "sunny patio"],
        reviewThemes: [{ theme: "calm space", sentiment: "pos", quote: "Great coffee, calm space to work." }],
        pricePosition: "mid",
        personality: ["cozy", "warm", "unhurried"],
        voice: "warm",
      },
      visual: {
        palette: {
          bg: "#faf6ef", surface: "#f1e9dc", ink: "#221c14", muted: "#655a49",
          accent: "#7a4a21", accentInk: "#ffffff", border: "rgba(34,28,20,0.14)",
          source: "agent-chosen",
          rationale: "Warm paper + espresso browns pulled from the roastery photos.",
        },
        typography: {
          display: "Fraunces", body: "Karla", displayTreatment: "normal",
          rationale: "Soft wonky serif for the bakery warmth, plain grotesque body.",
        },
        ornament: "grain",
        density: "airy",
        mood: "boutique",
        motif: "editorial-quote-slab",
        signatureMove: "A pull-quote hero — the neighborhood's own words open the page.",
        layoutDNA: {
          // "chapter" dividers exercise the label-dedup path (SOL critique):
          // the divider prints "The Menu", so the menu-board card must
          // suppress its own internal heading — never "THE MENU" twice.
          grid: "asymmetric-left", rhythm: "even", edgeTreatment: "contained",
          verticalTypography: "none", sectionDividers: "chapter", headerAlign: "left",
        },
        typeDNA: {
          scaleRatio: 1.414,
          heroSizeClass: "oversized",
          eyebrowTreatment: "rule-line",
          headingCase: "sentence",
          displayWeight: "semibold",
          displayTracking: "tight",
          bodyMeasure: "narrow",
        },
        gridFamily: "split-5-7",
        chrome: { nav: "center-stack", footer: "colophon" },
      },
      logo: { treatment: "wordmark-only", placement: "top-left", size: "sm", rationale: "No mark on file — set the name in the display face." },
      homepage: {
        hero: {
          variant: "editorial-quote",
          photoIntent: "morning light across the pour-over bar",
          headline: "House-roasted coffee and scratch-made pastries",
          sub: "Single-origin pour-overs, sourdough toasts, and a sunny patio.",
          trustChip: "rating",
        },
        cta: { primary: { label: "Visit Us", action: "visit" }, placement: "hero" },
        sections: ["hero", "cta-band", "menu-board", "story", "reviews", "hours-map", "social", "footer"],
      },
      content: {
        servicesFraming: "menu",
        servicesCount: 3,
        reviewsCount: 2,
        galleryIntent: ["pastry case", "patio"],
        aboutAngle: "the roasting-and-baking craft",
      },
      citations: [],
    },
  },
  // Composes an OVERLAY hero (photo-rich, media-forward) — exercises the
  // hero-CTA invariant on a photo: solid accent CTA + phone plate over the
  // even scrim (SOL screenshot critique fixes 1-2).
  {
    vertical: "restaurant-hospitality",
    businessName: "Auction House Food Hall",
    businessNameSource: "google_places",
    tagline: "Nine kitchens under one roof.",
    heroHeadline: "Nine local kitchens, one big room",
    heroSub: "Tacos, ramen, smash burgers, and a full bar in a converted auction house downtown.",
    ctaLabel: "Visit Us",
    services: [
      { name: "El Camino Tacos", blurb: "Birria and al pastor from the corner stall." },
      { name: "Slurp Ramen", blurb: "Tonkotsu and spicy miso bowls." },
      { name: "Stack'd Burgers", blurb: "Smash burgers with hand-cut fries." },
      { name: "The Gavel Bar", blurb: "Local drafts and frozen cocktails." },
      { name: "Sweet Stall", blurb: "Soft serve and hand pies." },
    ],
    about: "We're a food hall bringing nine independent local vendors together in a restored auction house.",
    hoursLine: "Open today 11am–10pm",
    serviceAreaLine: "Serving Greenville, SC",
    reviews: [
      { quote: "Something for everyone — we go every week.", author: "Renee P.", rating: 5 },
      { quote: "Loud and fun, great for groups.", author: "Miguel A.", rating: 4 },
      { quote: "The birria tacos are unreal.", author: "Sam K.", rating: 5 },
    ],
    phone: "(864) 555-0100",
    address: "23 Auction Way, Greenville, SC",
    photoUrls: photos("auctionhall", 7),
    rating: 4.6,
    reviewCount: 540,
    designBrief: {
      personality: ["lively", "casual", "social"],
      audience: "families and groups of friends",
      pricePosition: "mid",
      conversionGoal: "visit",
    },
  },

  // ── trades × 2 ─────────────────────────────────────────────────────
  {
    vertical: "trades",
    businessName: "RapidFlow Plumbing",
    businessNameSource: "intake",
    tagline: "Burst pipe? We're already on the way.",
    heroHeadline: "24/7 emergency plumbing, one call away",
    heroSub: "Licensed plumbers on call around the clock for bursts, backups, and water heaters.",
    ctaLabel: "Call Now",
    services: [
      { name: "Emergency Repairs", blurb: "24/7 response for bursts and major leaks." },
      { name: "Drain Cleaning", blurb: "Hydro-jetting and camera inspections." },
      { name: "Water Heaters", blurb: "Same-day replacement, tank and tankless." },
      { name: "Repiping", blurb: "Whole-home copper and PEX repipes." },
    ],
    about: "We're a licensed, insured plumbing crew built around fast emergency response at fair prices.",
    hoursLine: "Open 24 hours",
    serviceAreaLine: "Serving Knoxville, TN and 30 miles around",
    reviews: [
      { quote: "Showed up at 2am and saved our basement. Worth every penny.", author: "Gary D.", rating: 5 },
      { quote: "Fast, honest, and cleaned up after themselves.", author: "Lauren M.", rating: 5 },
    ],
    phone: "(865) 555-0166",
    address: null,
    photoUrls: photos("rapidflow", 1),
    rating: 4.9,
    reviewCount: 143,
    designBrief: {
      personality: ["fast", "reliable", "honest"],
      audience: "homeowners with urgent problems",
      pricePosition: "mid",
      conversionGoal: "call",
    },
  },
  {
    vertical: "trades",
    businessName: "Hearthstone Remodeling",
    businessNameSource: "site_title",
    tagline: "Considered renovations, built to last.",
    heroHeadline: "Kitchens and baths, designed and built in-house",
    heroSub: "A design-build studio for whole-room renovations with transparent fixed-bid quotes.",
    ctaLabel: "Get a Quote",
    services: [
      { name: "Kitchen Remodels", blurb: "Full-gut renovations with in-house design." },
      { name: "Bath Renovations", blurb: "Tile, glass, and custom vanities." },
      { name: "Built-Ins", blurb: "Cabinetry and shelving made to measure." },
      { name: "Design Consultations", blurb: "Fixed-fee planning before you commit." },
    ],
    about: "We're a design-build remodeling studio handling everything from drawings to final punch list in-house.",
    hoursLine: "Open today 8am–5pm",
    serviceAreaLine: "Serving Chattanooga, TN",
    reviews: [
      { quote: "Meticulous work and a schedule they actually kept.", author: "Whit F.", rating: 5 },
      { quote: "The design process alone was worth it.", author: "Joanne C.", rating: 5 },
    ],
    phone: "(423) 555-0119",
    address: "77 Foundry Row, Chattanooga, TN",
    photoUrls: photos("hearthstone", 5),
    rating: 4.8,
    reviewCount: 47,
    designBrief: {
      personality: ["meticulous", "polished", "professional"],
      audience: "homeowners planning major renovations",
      pricePosition: "premium",
      conversionGoal: "quote",
    },
  },

  // ── beauty-wellness ────────────────────────────────────────────────
  {
    vertical: "beauty-wellness",
    businessName: "Luxe & Lather Salon",
    businessNameSource: "google_places",
    tagline: "Unhurried appointments, undivided attention.",
    heroHeadline: "Color, cuts, and quiet luxury",
    heroSub: "A boutique salon with private chairs, botanical products, and appointments that never feel rushed.",
    ctaLabel: "Book Online",
    services: [
      { name: "Dimensional Color", blurb: "Balayage and foils tailored to your grow-out." },
      { name: "Precision Cuts", blurb: "Dry-cut finishing for your daily routine." },
      { name: "Keratin Smoothing", blurb: "Frizz control that lasts for months." },
      { name: "Bridal Styling", blurb: "Trials and day-of styling on location." },
    ],
    about: "We're a boutique salon focused on unhurried, personal appointments with premium botanical products.",
    hoursLine: "Open today 9am–7pm",
    serviceAreaLine: "Serving Charlotte, NC",
    reviews: [
      { quote: "The calmest salon experience I've ever had — and the best color.", author: "Imani J.", rating: 5 },
      { quote: "Worth booking weeks ahead. Ask for the keratin treatment.", author: "Sofia R.", rating: 5 },
    ],
    phone: "(704) 555-0155",
    address: "310 Elm St, Charlotte, NC",
    photoUrls: photos("luxelather", 4),
    rating: 4.9,
    reviewCount: 210,
    designBrief: {
      personality: ["calming", "refined", "personal"],
      audience: "clients who book ahead for self-care",
      pricePosition: "premium",
      conversionGoal: "book",
    },
  },

  // ── fitness ────────────────────────────────────────────────────────
  {
    vertical: "fitness",
    businessName: "Ironworks Strength Club",
    businessNameSource: "intake",
    tagline: "Lift heavy. Leave better.",
    heroHeadline: "Strength classes that actually program progress",
    heroSub: "Coached barbell classes Monday 6:00am through Saturday 10:00am, capped at twelve athletes.",
    ctaLabel: "Book a Visit",
    services: [
      { name: "Barbell Foundations", blurb: "Mon 6:00am · learn the big lifts safely." },
      { name: "Strength Cycle", blurb: "Wed 5:30pm · periodized squat and press work." },
      { name: "Conditioning", blurb: "Fri 6:00am · sleds, carries, and intervals." },
      { name: "Open Gym", blurb: "Sat 10:00am · coached open platform time." },
    ],
    about: "We're a coached strength club running small-group barbell classes on a real progression program.",
    hoursLine: "Open today 6am–8pm",
    serviceAreaLine: "Serving Johnson City, TN",
    reviews: [
      { quote: "First gym where I actually got stronger month over month.", author: "Blake N.", rating: 5 },
      { quote: "Coaches watch every rep. Small classes are the difference.", author: "Erin V.", rating: 5 },
    ],
    phone: "(423) 555-0182",
    address: "12 Foundry St, Johnson City, TN",
    photoUrls: photos("ironworks", 5),
    rating: 4.9,
    reviewCount: 76,
    designBrief: {
      personality: ["intense", "supportive", "driven"],
      audience: "committed lifters and beginners alike",
      pricePosition: "mid",
      conversionGoal: "book",
    },
  },

  // ── auto-carwash × 2 ───────────────────────────────────────────────
  {
    vertical: "auto-carwash",
    businessName: "SudsUp Express Wash",
    businessNameSource: "google_places",
    tagline: "Three minutes. Spotless.",
    heroHeadline: "Unlimited washes from $19 a month",
    heroSub: "Drive-through tunnel wash with free vacuums, three membership tiers, and no lines after 4pm.",
    ctaLabel: "Call Now",
    services: [
      { name: "Basic Wash", blurb: "Soft-touch tunnel wash and spot-free rinse." },
      { name: "Pro Shine", blurb: "Adds triple foam, wheel blast, and tire gloss." },
      { name: "Ultimate Package", blurb: "Ceramic sealant, rain repellent, underbody flush." },
      { name: "Free Vacuums", blurb: "High-suction stalls with every wash." },
    ],
    about: "We're an express tunnel wash built for speed — unlimited plans, free vacuums, and a spotless finish.",
    hoursLine: "Open today 7am–8pm",
    serviceAreaLine: "Serving Spartanburg, SC",
    reviews: [
      { quote: "Fastest wash in town and the membership pays for itself.", author: "Deon C.", rating: 5 },
      { quote: "Vacuums actually work. Rare.", author: "Katie B.", rating: 4 },
    ],
    phone: "(864) 555-0190",
    address: "1500 Bypass Rd, Spartanburg, SC",
    photoUrls: photos("sudsup", 3),
    rating: 4.5,
    reviewCount: 388,
    designBrief: {
      personality: ["quick", "cheap", "friendly"],
      audience: "commuters who wash weekly",
      pricePosition: "budget",
      conversionGoal: "call",
    },
  },
  {
    vertical: "auto-carwash",
    businessName: "Precision Auto Care",
    businessNameSource: "site_title",
    tagline: "Dealer-level service without the dealer.",
    heroHeadline: "Honest diagnostics and repairs done right",
    heroSub: "ASE-certified techs, straight talk, and photos of every repair before we start the work.",
    ctaLabel: "Call Now",
    services: [
      { name: "Diagnostics", blurb: "Full-system scans with photo reports." },
      { name: "Brakes & Suspension", blurb: "Pads, rotors, struts, and alignments." },
      { name: "Oil & Fluids", blurb: "Full-synthetic changes while you wait." },
      { name: "Pre-Purchase Inspections", blurb: "Know before you buy a used car." },
    ],
    about: "We're an independent shop doing dealer-level diagnostics with honest recommendations and no upsells.",
    hoursLine: "Open today 8am–6pm",
    serviceAreaLine: "Serving Asheville, NC",
    reviews: [
      { quote: "They showed me photos of the worn part before touching anything.", author: "Nate O.", rating: 5 },
      { quote: "Fair prices, no pressure, fixed right the first time.", author: "Carmen E.", rating: 5 },
    ],
    phone: "(828) 555-0148",
    address: "40 Sweeten Creek Rd, Asheville, NC",
    photoUrls: photos("precisionauto", 2),
    rating: 4.7,
    reviewCount: 165,
    designBrief: {
      personality: ["honest", "thorough", "dependable"],
      audience: "drivers tired of dealership pricing",
      pricePosition: "mid",
      conversionGoal: "call",
    },
  },

  // ── generic × 2 ────────────────────────────────────────────────────
  {
    vertical: "generic",
    businessName: "Kessler & Grant Law",
    businessNameSource: "site_title",
    tagline: "Measured counsel for consequential moments.",
    heroHeadline: "Estate planning handled with quiet precision",
    heroSub: "A two-partner firm for wills, trusts, and probate — flat fees quoted up front.",
    ctaLabel: "Contact Us",
    services: [
      { name: "Wills & Trusts", blurb: "Plans matched to your family and assets." },
      { name: "Probate", blurb: "Steady guidance through the court process." },
      { name: "Elder Law", blurb: "Care planning and guardianship counsel." },
    ],
    about: "We're a boutique estate-planning firm offering flat-fee engagements and unhurried counsel.",
    hoursLine: "Open today 9am–5pm",
    serviceAreaLine: "Serving Winston-Salem, NC",
    reviews: [
      { quote: "Explained everything plainly and quoted the fee up front.", author: "Harold B.", rating: 5 },
    ],
    phone: "(336) 555-0130",
    address: "500 W 4th St, Winston-Salem, NC",
    photoUrls: [],
    rating: 5.0,
    reviewCount: 18,
    designBrief: {
      personality: ["refined", "measured", "trustworthy"],
      audience: "families planning their estates",
      pricePosition: "premium",
      conversionGoal: "call",
    },
  },
  {
    vertical: "generic",
    businessName: "Happy Tails Dog Sitting",
    businessNameSource: "intake",
    tagline: "Walks, wags, and daily photo updates.",
    heroHeadline: "Your dog's second-favorite people",
    heroSub: "Insured in-home sitting and daily walks with GPS check-ins and photo updates every visit.",
    ctaLabel: "Get Started",
    services: [
      { name: "Daily Walks", blurb: "30- or 60-minute neighborhood walks." },
      { name: "In-Home Sitting", blurb: "Overnight care in your dog's own space." },
      { name: "Puppy Visits", blurb: "Midday breaks, feeding, and play." },
      { name: "Pet Taxi", blurb: "Rides to the vet or groomer." },
    ],
    about: "We're a small insured pet-care team sending photo updates and GPS check-ins with every single visit.",
    hoursLine: "Open today 7am–9pm",
    serviceAreaLine: "Serving Boone, NC and 15 miles around",
    reviews: [
      { quote: "The photo updates make leaving town so much easier.", author: "Mel T.", rating: 5 },
      { quote: "Reliable, sweet with our anxious rescue.", author: "Jordan F.", rating: 5 },
    ],
    phone: "(828) 555-0173",
    address: null,
    photoUrls: photos("happytails", 4),
    rating: 4.9,
    reviewCount: 52,
    designBrief: {
      personality: ["friendly", "playful", "trustworthy"],
      audience: "busy dog owners",
      pricePosition: "mid",
      conversionGoal: "book",
    },
  },
];
