export type Feature = {
  slug: string;
  icon: "globe" | "phone" | "pen" | "map";
  title: string;
  navLabel: string;
  hero: string;
  tagline: string;
  summary: string;
  pains: { stat: string; label: string }[];
  sections: { title: string; body: string }[];
  bullets: string[];
  priceContext: string;
  cta: { label: string; href: string };
};

export const features: Feature[] = [
  {
    slug: "ai-websites",
    icon: "globe",
    title: "AI Website Generation",
    navLabel: "AI Websites",
    hero: "Your website is already built. You just haven't seen it yet.",
    tagline: "Conversion-optimized sites generated from your real business data.",
    summary:
      "We pull your Google Maps listing — photos, reviews, hours, and services — and generate a complete, conversion-optimized website before you ever fill out a form.",

    pains: [
      { stat: "40%", label: "of service businesses have an outdated or missing website" },
      { stat: "0.05s", label: "for a visitor to form a first impression of your business" },
      { stat: "$5k–$15k", label: "what a traditional agency charges for a comparable build" },
    ],
    sections: [
      {
        title: "Built from data, not questionnaires",
        body: "Most builders start with a blank template and a 40-question intake form. We start with what your customers already see about your business: verified address, service categories, photos, star rating, review excerpts, and working hours — assembled into a 10–15 page site structured for local search.",
      },
      {
        title: "Copy written for your trade, by AI",
        body: "Every headline, service description, and call-to-action is generated by large language models using your industry, city, and competitive landscape as context — then screened by a three-judge LLM quality panel before anything goes live.",
      },
      {
        title: "Live in 24 hours",
        body: "Because your site is pre-built during the preview phase, going live is a switch-flip, not a six-week project. Hosting, SSL, monitoring, and security patches are included on every plan.",
      },
    ],
    bullets: [
      "10–15 page conversion-optimized architecture",
      "Real photos, reviews, and hours pulled from your listing",
      "Mobile-first, Core Web Vitals > 90",
      "Hosting, SSL, and uptime monitoring included",
      "AI copy screened by a 3-judge quality panel",
      "Design refresh included every year",
    ],
    priceContext:
      "Included in every plan — from the $150/month Starter to the $15,000 Mega Package.",
    cta: { label: "See a live preview of your site", href: "/demo" },
  },
  {
    slug: "voice-agent",
    icon: "phone",
    title: "AI Voice Receptionist",
    navLabel: "Voice Agent",
    hero: "Never miss another lead. 24/7 AI voice booking.",
    tagline: "Answers every call, books appointments, and never puts anyone on hold.",
    summary:
      "85% of customers whose calls go unanswered never call back — they call the next business on Google. Our AI voice agent answers in a natural voice, books the job, and texts back every missed call.",
    pains: [
      { stat: "85%", label: "of unanswered callers never call back" },
      { stat: "30%", label: "of calls the average service business misses" },
      { stat: "$200–$500", label: "revenue lost with every missed call" },
    ],
    sections: [
      {
        title: "A receptionist that never sleeps",
        body: "The agent answers in a natural voice trained on your industry — services, pricing ranges, service area, and FAQs. It books directly into Google Calendar, Calendly, or your industry CRM, and hands off gracefully to a human for complex calls.",
      },
      {
        title: "Missed-call text-back",
        body: "If a caller hangs up or your line is busy, they get a text within 30 seconds: “Sorry we missed you — want us to book you in?” That single automation recovers jobs that used to vanish.",
      },
      {
        title: "Every call recorded and measured",
        body: "Calls are recorded, transcribed, and scored. Your monthly report shows calls handled, appointments booked, and revenue attributed — so the ROI is never a guess.",
      },
    ],
    bullets: [
      "Natural-voice answering, 24/7/365",
      "Books into Google Calendar, Calendly, or your CRM",
      "Missed-call text-back within 30 seconds",
      "Website chatbot trained on your business",
      "Call recording, transcription, and analytics",
      "Human escalation paths for complex calls",
    ],
    priceContext:
      "A human receptionist costs $3,000+/month. Our AI costs $292/month — and handles unlimited simultaneous calls.",
    cta: { label: "Add AI Voice Agent — $3,500/year", href: "/pricing" },
  },
  {
    slug: "automated-seo",
    icon: "pen",
    title: "Automated SEO & Content",
    navLabel: "Automated SEO",
    hero: "Your competitors post monthly. Your site posts weekly. Automatically.",
    tagline: "LLM-written, quality-judged content that compounds your rankings.",
    summary:
      "Search engines reward businesses that publish consistently. Our content engine writes SEO-optimized blog posts, service pages, and Google Business Profile updates for your exact trade and city — every week, without you lifting a finger.",
    pains: [
      { stat: "$500–$2,000", label: "what agencies charge per month for content" },
      { stat: "3×", label: "more organic traffic for businesses that blog consistently" },
      { stat: "0 hrs", label: "of your time required per week" },
    ],
    sections: [
      {
        title: "Content tuned to your trade and town",
        body: "“5 Signs Your AC Needs Repair This Summer” for a Phoenix HVAC company. “How Often Should You Reseal a Driveway in New England?” for a Boston paving contractor. Every post uses your services, location, and competitors as context.",
      },
      {
        title: "A three-judge quality panel",
        body: "Every piece of content passes a panel of three independent LLM judges checking accuracy, tone, and brand alignment before publication. Content that doesn't pass doesn't publish.",
      },
      {
        title: "Signals across the whole surface",
        body: "Weekly blog posts, locally-optimized service pages, weekly Google Business Profile posts, and citation building across the top 30 directories — every ranking signal, maintained on schedule.",
      },
    ],
    bullets: [
      "Weekly SEO blog posts (bi-weekly on maintenance)",
      "Locally-optimized service pages per city",
      "Weekly Google Business Profile posts",
      "Citations across top 30 directories",
      "3-judge LLM quality panel on all content",
      "Monthly traffic and ranking reports",
    ],
    priceContext:
      "Included in the Core Agency Package ($5,000 first year) — a service agencies bill $6,000–$24,000/year for.",
    cta: { label: "See Core Package pricing", href: "/pricing" },
  },
  {
    slug: "google-maps",
    icon: "map",
    title: "Google Maps Dominance",
    navLabel: "Maps Dominance",
    hero: "Top 3 in Google Maps in 20 weeks. Guaranteed.",
    tagline: "An aggressive, timeline-bound campaign to own your local market.",
    summary:
      "The Maps 3-pack captures the overwhelming majority of local clicks and calls. Our Mega Package runs a 20-week campaign — citations, reviews, content, and competitor displacement — with a performance guarantee.",
    pains: [
      { stat: "~70%", label: "of local clicks go to the Maps 3-pack" },
      { stat: "$1.5k–$5k/mo", label: "what agencies charge for local SEO retainers" },
      { stat: "20 wks", label: "our timeline to Top 3 — or we keep working free" },
    ],
    sections: [
      {
        title: "200+ citations, built and managed",
        body: "Consistent name-address-phone data across 200+ directories is table stakes for Maps ranking. We build, verify, and maintain them automatically.",
      },
      {
        title: "Reviews on autopilot",
        body: "Automated post-service review request sequences turn happy customers into ranking fuel. Review velocity is one of the strongest local signals — and most businesses leave it to chance.",
      },
      {
        title: "Competitor displacement",
        body: "We analyze the current 3-pack occupants for your keywords, find their weaknesses — thin content, stale reviews, missing categories — and systematically target them. Bi-weekly strategy calls keep you in the loop for all 20 weeks.",
      },
    ],
    bullets: [
      "20-week timeline-bound SEO campaign",
      "200+ citations built and managed",
      "Automated review generation sequences",
      "Competitor analysis and displacement targeting",
      "Local PR syndication and backlinks",
      "Top 3 guarantee — or we keep working at no cost",
    ],
    priceContext:
      "The Mega Package is $15,000 fixed — comparable agency campaigns run $7,500–$25,000 with no guarantee.",
    cta: { label: "Explore the Mega Package", href: "/pricing" },
  },
];

export function getFeature(slug: string) {
  return features.find((f) => f.slug === slug);
}
