/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoGalleryRouteImport } from './routes/demo-gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminDemoRunsRouteImport } from './routes/admin.demo-runs'
import { Route as AdminDesignTelemetryRouteImport } from './routes/admin.design-telemetry'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as LegalAiEthicsRouteImport } from './routes/legal.ai-ethics'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAnalyticsRouteImport } from './routes/portal.analytics'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as PortalContentRouteImport } from './routes/portal.content'
import { Route as PortalVoiceAgentRouteImport } from './routes/portal.voice-agent'
import { Route as AdminCrmIndexRouteImport } from './routes/admin.crm.index'
import { Route as AdminCrmLeadIdRouteImport } from './routes/admin.crm.$leadId'
import { Route as AdminCrmBoardRouteImport } from './routes/admin.crm.board'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGalleryRoute = DemoGalleryRouteImport.update({
  id: '/demo-gallery',
  path: '/demo-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRunsRoute = AdminDemoRunsRouteImport.update({
  id: '/admin/demo-runs',
  path: '/admin/demo-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignTelemetryRoute = AdminDesignTelemetryRouteImport.update({
  id: '/admin/design-telemetry',
  path: '/admin/design-telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAiEthicsRoute = LegalAiEthicsRouteImport.update({
  id: '/legal/ai-ethics',
  path: '/legal/ai-ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContentRoute = PortalContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVoiceAgentRoute = PortalVoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => PortalRoute,
} as any)
const AdminCrmIndexRoute = AdminCrmIndexRouteImport.update({
  id: '/admin/crm/',
  path: '/admin/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmLeadIdRoute = AdminCrmLeadIdRouteImport.update({
  id: '/admin/crm/$leadId',
  path: '/admin/crm/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmBoardRoute = AdminCrmBoardRouteImport.update({
  id: '/admin/crm/board',
  path: '/admin/crm/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/demo-gallery': typeof DemoGalleryRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/status': typeof StatusRoute
  '/admin/demo-runs': typeof AdminDemoRunsRoute
  '/admin/design-telemetry': typeof AdminDesignTelemetryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/ai-ethics': typeof LegalAiEthicsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/voice-agent': typeof PortalVoiceAgentRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/crm/board': typeof AdminCrmBoardRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/demo-gallery': typeof DemoGalleryRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/status': typeof StatusRoute
  '/admin/demo-runs': typeof AdminDemoRunsRoute
  '/admin/design-telemetry': typeof AdminDesignTelemetryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/ai-ethics': typeof LegalAiEthicsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/voice-agent': typeof PortalVoiceAgentRoute
  '/blog': typeof BlogIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/crm/board': typeof AdminCrmBoardRoute
  '/admin/crm': typeof AdminCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/demo-gallery': typeof DemoGalleryRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/status': typeof StatusRoute
  '/admin/demo-runs': typeof AdminDemoRunsRoute
  '/admin/design-telemetry': typeof AdminDesignTelemetryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/ai-ethics': typeof LegalAiEthicsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/voice-agent': typeof PortalVoiceAgentRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/crm/board': typeof AdminCrmBoardRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/demo-gallery'
    | '/login'
    | '/partners'
    | '/portal'
    | '/pricing'
    | '/roi-calculator'
    | '/status'
    | '/admin/demo-runs'
    | '/admin/design-telemetry'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/features/$slug'
    | '/industries/$slug'
    | '/legal/ai-ethics'
    | '/legal/privacy'
    | '/legal/terms'
    | '/portal/analytics'
    | '/portal/billing'
    | '/portal/content'
    | '/portal/voice-agent'
    | '/blog/'
    | '/features/'
    | '/industries/'
    | '/portal/'
    | '/admin/crm/$leadId'
    | '/admin/crm/board'
    | '/admin/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/demo-gallery'
    | '/login'
    | '/partners'
    | '/pricing'
    | '/roi-calculator'
    | '/status'
    | '/admin/demo-runs'
    | '/admin/design-telemetry'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/features/$slug'
    | '/industries/$slug'
    | '/legal/ai-ethics'
    | '/legal/privacy'
    | '/legal/terms'
    | '/portal/analytics'
    | '/portal/billing'
    | '/portal/content'
    | '/portal/voice-agent'
    | '/blog'
    | '/features'
    | '/industries'
    | '/portal'
    | '/admin/crm/$leadId'
    | '/admin/crm/board'
    | '/admin/crm'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/demo-gallery'
    | '/login'
    | '/partners'
    | '/portal'
    | '/pricing'
    | '/roi-calculator'
    | '/status'
    | '/admin/demo-runs'
    | '/admin/design-telemetry'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/features/$slug'
    | '/industries/$slug'
    | '/legal/ai-ethics'
    | '/legal/privacy'
    | '/legal/terms'
    | '/portal/analytics'
    | '/portal/billing'
    | '/portal/content'
    | '/portal/voice-agent'
    | '/blog/'
    | '/features/'
    | '/industries/'
    | '/portal/'
    | '/admin/crm/$leadId'
    | '/admin/crm/board'
    | '/admin/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DemoGalleryRoute: typeof DemoGalleryRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  StatusRoute: typeof StatusRoute
  AdminDemoRunsRoute: typeof AdminDemoRunsRoute
  AdminDesignTelemetryRoute: typeof AdminDesignTelemetryRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LegalAiEthicsRoute: typeof LegalAiEthicsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  AdminCrmLeadIdRoute: typeof AdminCrmLeadIdRoute
  AdminCrmBoardRoute: typeof AdminCrmBoardRoute
  AdminCrmIndexRoute: typeof AdminCrmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-gallery': {
      id: '/demo-gallery'
      path: '/demo-gallery'
      fullPath: '/demo-gallery'
      preLoaderRoute: typeof DemoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo-runs': {
      id: '/admin/demo-runs'
      path: '/admin/demo-runs'
      fullPath: '/admin/demo-runs'
      preLoaderRoute: typeof AdminDemoRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/design-telemetry': {
      id: '/admin/design-telemetry'
      path: '/admin/design-telemetry'
      fullPath: '/admin/design-telemetry'
      preLoaderRoute: typeof AdminDesignTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/ai-ethics': {
      id: '/legal/ai-ethics'
      path: '/legal/ai-ethics'
      fullPath: '/legal/ai-ethics'
      preLoaderRoute: typeof LegalAiEthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/content': {
      id: '/portal/content'
      path: '/content'
      fullPath: '/portal/content'
      preLoaderRoute: typeof PortalContentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/voice-agent': {
      id: '/portal/voice-agent'
      path: '/voice-agent'
      fullPath: '/portal/voice-agent'
      preLoaderRoute: typeof PortalVoiceAgentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/crm/': {
      id: '/admin/crm/'
      path: '/admin/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminCrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/$leadId': {
      id: '/admin/crm/$leadId'
      path: '/admin/crm/$leadId'
      fullPath: '/admin/crm/$leadId'
      preLoaderRoute: typeof AdminCrmLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/board': {
      id: '/admin/crm/board'
      path: '/admin/crm/board'
      fullPath: '/admin/crm/board'
      preLoaderRoute: typeof AdminCrmBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalBillingRoute: typeof PortalBillingRoute
  PortalContentRoute: typeof PortalContentRoute
  PortalVoiceAgentRoute: typeof PortalVoiceAgentRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalBillingRoute: PortalBillingRoute,
  PortalContentRoute: PortalContentRoute,
  PortalVoiceAgentRoute: PortalVoiceAgentRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DemoGalleryRoute: DemoGalleryRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  StatusRoute: StatusRoute,
  AdminDemoRunsRoute: AdminDemoRunsRoute,
  AdminDesignTelemetryRoute: AdminDesignTelemetryRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LegalAiEthicsRoute: LegalAiEthicsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  AdminCrmLeadIdRoute: AdminCrmLeadIdRoute,
  AdminCrmBoardRoute: AdminCrmBoardRoute,
  AdminCrmIndexRoute: AdminCrmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
